on: [push]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      # found in https://github.com/rusnasonov/vscode-hugo/blob/master/.github/workflows/build.yml
      - name: version number
        id: version_number
        run: |
          echo "##[set-output name=version;]$(date +%Y%m%d%S)"

      - name: Build project
        run: |
          zip --junk-paths my-artifact README.md

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Create Release
        if: success() && !startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_number.outputs.version }}
          release_name: Release ${{ steps.version_number.outputs.version }}
          draft: false
          prerelease: true
      - name: Get upload URL
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          UPLOAD_URL=$(curl -s https://api.github.com/repos/${{github.repository}}/releases/latest | jq .upload_url)
          echo "##[set-env name=upload_url;]$UPLOAD_URL"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ join(steps.create_release.outputs.upload_url, env.upload_url) }}
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
